import { VerticalBox, Button, HorizontalBox, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 450px;
    height: 600px;
    background: white;
    in property <[string]> items;
    callback clear-all();
    default-font-family: "Heiti SC";

    VerticalBox {
        alignment: start;
        HorizontalBox {
            TextInput {
                text: "Filter ";
                color: black;
                wrap: word-wrap;

                private property <length> margin: 1rem;
                cursor-position-changed(cursor-position) => {
                    if cursor-position.x + self.x < margin {
                        self.x = - cursor-position.x + margin;
                    } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                        self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
                    }
                }
            }
            Button {
                text: "全部清除";
                width: 80px;
                clicked => {
                    root.clear-all();
                }
            }
        }
        ScrollView {
            width: parent.width;
            height: parent.height - 50px;
            VerticalBox {
                for item in root.items: Rectangle {
                    width: 400px;
                    height: 40px;
                    background: white;
                    border-color: #e1e1e1;
                    border-width: 1px;
                    clip: true;
                    Text { 
                        x: 10px;
                        y: 0px;
                        width: 390px;
                        height: 40px;
                        text: item;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        color: black;
                    }
                }
            }
        }

    }
}
